### ISSUE TITLE
Edit page means broken link (404)

### ISSUE THREAD

**Issue by baumannzone** [leerob/react2025#53]
I'm reading the docs of the course in Spanish.

When I try to edit any doc page, I got a "not found" error message:

Doc page: https://docs.react2025.com/es/firebase/use-auth (happens in every page, when trying to edit on GitHub, using the link in the footer of each page)
<img width="636" alt="image" src="https://user-images.githubusercontent.com/5422102/193934786-db19c67e-2344-48d6-8157-8cff7510faee.png">

Error page: https://github.com/leerob/react2025/blob/main/pages/firebase/use-auth.es.md
<img width="1484" alt="image" src="https://user-images.githubusercontent.com/5422102/193934413-006f17be-f998-47b3-9066-cea1db80fc54.png">

It seems to be that the original folder or path changed and it needs to be updated somewhere.

**Comment by baumannzone** [comment]
I just figured out this line, in the theme config file,

https://github.com/leerob/react2025/blob/main/docs/theme.config.js#L12

may be the problem (?)

**Comment by leerob** [comment]
Closing as I've made a new repo with updated patterns 😄 

https://github.com/leerob/react2025/commit/4a9b12deba9d2e47c1e630239490639921bf748d
https://github.com/leerob/next-saas-starter
