### ISSUE TITLE
Text on landing page is rendered in the wrong font

### ISSUE THREAD

**Issue by akd-io** [leerob/react2025#58]
Fonts look like this on my machine:
![Screenshot 2022-12-03 at 20 40 32](https://user-images.githubusercontent.com/30059155/205458870-27bc638c-45ca-4f40-af44-c7b2d6e96d98.png)

Inspecting heading styles show:
![Screenshot 2022-12-03 at 20 42 04](https://user-images.githubusercontent.com/30059155/205458927-a2adba62-5773-4f5d-a640-8dd8805d7e06.png)

The font-family seems to be overridden by either tailwindcss or modern-normalize

**Comment by leerob** [comment]
This is just `font-display: optional` 👍 It's appearing correctly for me.

**Comment by akd-io** [comment]
I know you're super busy, but I sincerely think there's still a problem. If you have 5 min I'd love to learn if I'm wrong.

I can't find any `font-display: optional` in any of your sources, and nothing changes on subsequent page loads.

Your Inter font is referenced with `display=swap` but doesn't load for me (in the Network tab) in neither Chrome nor Safari. Safari renders `.SF NS` while Chrome renders `Times`.
